### PR TITLE
Init demo content

### PR DESCRIPTION
**Pull request by aleevas**
Jira issues: 
- [DS-1042](https://yusa.atlassian.net/browse/DS-1042)
- [DS-1097](https://yusa.atlassian.net/browse/DS-1097)
-  [DS-1043](https://yusa.atlassian.net/browse/DS-1043)
-  [DS-1044](https://yusa.atlassian.net/browse/DS-1044)
-  [DS-1045](https://yusa.atlassian.net/browse/DS-1045)
-  [DS-1046](https://yusa.atlassian.net/browse/DS-1046)
-  [DS-1047](https://yusa.atlassian.net/browse/DS-1047)
-  [DS-1048](https://yusa.atlassian.net/browse/DS-1048)
-  [DS-1088](https://yusa.atlassian.net/browse/DS-1088)
- [DS-1089](https://yusa.atlassian.net/browse/DS-1089)
- [DS-1090](https://yusa.atlassian.net/browse/DS-1090)
- [DS-1091](https://yusa.atlassian.net/browse/DS-1091)
- [DS-1092](https://yusa.atlassian.net/browse/DS-1092)
- [DS-1093](https://yusa.atlassian.net/browse/DS-1093)
- [DS-1094](https://yusa.atlassian.net/browse/DS-1094)
- [DS-1095](https://yusa.atlassian.net/browse/DS-1095)
- [DS-1096](https://yusa.atlassian.net/browse/DS-1096)
- [DS-1098](https://yusa.atlassian.net/browse/DS-1098)

How to check:

```sh
drush en y_lb_init_demo_content -y
drush migrate:import --group y_lb_init_demo_content
```

 - go to admin/modules
 - enable the Y Layout Builder - Init Demo Pages module
 - go to /admin/structure/migrate/manage/y_lb_init_demo_content/migrations
 - run this migration /admin/structure/migrate/manage/y_lb_init_demo_content/migrations/y_lb_init_demo_media_image/execute
 - run these migrations : 
    -  /admin/structure/migrate/manage/y_lb_init_demo_content/migrations/y_lb_init_demo_homepage/execute
    - /admin/structure/migrate/manage/y_lb_init_demo_content/migrations/y_lb_init_demo_page_who_we_are/execute
    - /admin/structure/migrate/manage/y_lb_init_demo_content/migrations/y_lb_init_demo_page_programs_overview/execute
    - /admin/structure/migrate/manage/y_lb_init_demo_content/migrations/y_lb_init_demo_page_programs_category/execute
 -  as alternative you can run this drush command: `drush migrate:import --group y_lb_init_demo_content`
 - go to /admin/content
 - visit all page with prefix in the title " Init Demo"
 - verify that pages looks like on design

### CODE REVIEW

**Comment by podarok** [comment]
@aleevas I guess we can simplify steps to test by providing one line drush command to import migration group

**Comment by aleevas** [comment]
> @aleevas I guess we can simplify steps to test by providing one line drush command to import migration group

@podarok Sure, but I thought that the QA engineer didn't have access to drush

The Drush commands are:
`drush en y_lb_init_demo_content -y  `
`drush migrate:import --group y_lb_init_demo_content`

**Comment by podarok** [comment]
@aleevas we'll automate this on sandboxes

**Comment by podarok** [comment]
@aleevas here is where we can add this group and have it on build in PR without need of merging to main branch https://github.com/YCloudYUSA/yusaopeny/blob/main/openy.profile#L350

**Comment by froboy** [comment]
@aleevas this is working on a clean install, but if I've created any content prior, I seem to get a conflict, like so:

```
 [notice] Processed 3 items (3 created, 0 updated, 0 failed, 0 ignored) - done with 'y_lb_init_demo_block_partners'
  1/12 [==>-------------------------]   8% [error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '126' for key 'block_content__revision_id': INSERT INTO "block_content" ("id", "revision_id", "type", "uuid", "langcode") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array
(
    [:db_insert_placeholder_0] => 126
    [:db_insert_placeholder_1] => 126
    [:db_insert_placeholder_2] => lb_ping_pong
    [:db_insert_placeholder_3] => 0ce0cba7-fef3-4016-9ebc-061b1eff95dd
    [:db_insert_placeholder_4] => en
)
 in Drupal\mysql\Driver\Database\mysql\ExceptionHandler->handleExecutionException() (line 43 of /var/www/docroot/core/modules/mysql/src/Driver/Database/mysql/ExceptionHandler.php). 
```

not sure if there's an easy workaround there.

**Comment by froboy** [comment]
I know this is still a WIP, but I wanted to check it out :) Things are looking really great overall! I think only one piece of feedback so far, apart from the error above:

Ping-pong blocks should probably always be in a full-width section

Cursor_and_Init_Demo_Home_Page___YMCA_OF__SPRINGFIELD_

**Comment by AnastasiiaPys** [comment]
retest this please

**Pull request merged**
